PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Hi, {PLAYER}!\p"
    .string "My brother, {RIVAL}, is out at\n"
    .string "Grandpa's LAB.$"

NINA: Salut [player]!\pn
Mon frère, [rival], est au\n
LABO de Papy.

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, I heard you had\n"
    .string "a battle against {RIVAL}.\p"
    .string "I wish I'd seen that!$"

NINA: [player], j'ai su que\n
tu as combattu [rival].\pn
J'aurais aimé voir ça!

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Grandpa asked you to run an\n"
    .string "errand?\p"
    .string "Gee, that's lazy of him.\n"
    .string "Here, this will help you.$"

Papy t'a demandé un\n
truc?\pn
Pah, il est feignant.\n
Tiens, ça t'aidera.

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} received a TOWN MAP\n"
    .string "from DAISY.$"

[player] a reçu une CARTE\n
de NINA.

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "You don't have space for this in\n"
    .string "your BAG.$"

Tu n'as pas de place pour ça\n
ton SAC.

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "You can use the TOWN MAP to find\n"
    .string "out where you are, or check the\l"
    .string "names of places.$"

Tu peux voir la CARTE pour\n
où tu es, ou voir les\l
noms des lieux.

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Just like people, POKéMON\n"
    .string "are living things.\p"
    .string "When they get tired, please give\n"
    .string "them a rest.$"

NINA: Comme les gens, PKM\n
sont vivants.\pn
S'ils fatiguent, laisse\n
les reposer.

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "It's a big map of the KANTO region.\n"
    .string "Now this would be useful!$"

C'est une carte de KANTO.\n
Ca pourrait être utile!

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "The shelves are crammed full of\n"
    .string "books on POKéMON.$"

Les étagères sont pleines\n
de livres sur PKM.

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Hi, {PLAYER}!\n"
    .string "Good timing.\p"
    .string "I'm about to have some tea.\n"
    .string "Would you like to join me?\p"
    .string "Oh, but look.\n"
    .string "Your POKéMON are a little dirty.\p"
    .string "Would you like me to groom one?$"

NINA: Salut [player]!\n
Timing OK.\pn
J'allais prendre du thé.\n
Tu veux te joindre à moi?\pn
Oh, regarde.\n
Tes PKM sont un peu sales.\pn
Tu veux que j'en toilette un?

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "You don't need any grooming done?\n"
    .string "Okay, we'll just have tea.$"

Pas besoin de toilettage?\n
OK, on prendra du thé.

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Which one should I groom?$"

Lequel je toilette?

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Okay, I'll get it looking\n"
    .string "nice in no time.$"

NINA: OK, il sera joli\n
en un instant.

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} looks dreamily content…\p"
    .string "{COLOR RED}DAISY: There you go! All done.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} looks dreamily content…\p"
    .string "{FONT_FEMALE}DAISY: There you go! All done.\n"
#endif
    .string "See? Doesn't it look nice?\p"
    .string "Giggle…\n"
    .string "It's such a cute POKéMON.$"

{COLOR DARK_GRAY}[STR_VAR_1] a l'air ravi\.\pn
{COLOR RED}NINA: Et voilà! Fini.\n
Tu vois? Il est beau?\pn
Hihi\.\n
C'est un si chou PKM.

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Oh, sorry. I honestly can't\n"
    .string "groom an EGG.$"

Oh, pardon. Je ne peux\n
toilett. OEUF

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Your POKéMON grow to love\n"
    .string "you if you raise them with love.\p"
    .string "For example, {PLAYER}, may I see\n"
    .string "your first POKéMON?$"

NINA: Tes PKM t'aiment\n
si tu les élèves avec amour.\pn
Par ex, [player], je peux\n
voir ton 1er PKM?

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "It couldn't possibly love you\n"
    .string "any more than it does now.\p"
    .string "Your POKéMON is happy beyond\n"
    .string "words.$"

Il ne peut pas t'aimer\n
plus qu'il le fait.\pn
Ton PKM est si heureux\n
.

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "It looks very happy.\p"
    .string "I wish {RIVAL} could see this and\n"
    .string "learn something from it.$"

Il a l'air ravi.\pn
Si [rival] pouvait voir\n
ça pour apprendre.

PalletTown_RDvalsHouse_Text_ItsQuiteFriendly::
    .string "It's quite friendly with you.\n"
    .string "Keep being good to it!$"

Il est ami avec toi.\n
Sois bon avec lui!

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "It's warming up to you.\n"
    .string "Trust must be growing between you.$"

Il s'ouvre à toi.\n
La confiance grandit.

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "It's not quite familiar with you\n"
    .string "yet.\p"
    .string "POKéMON are all quite wary when\n"
    .string "you first get them.$"

Il te connait peu.\n
\pn
Les PKM sont méfiants\n
au début.

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, I don't like the way it\n"
    .string "glares at you.\p"
    .string "Could you try being a little nicer\n"
    .string "to it?$"

[player], je n'aime pas\n
son regard.\pn
Essaie d'être un peu\n
cool?

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Um, it's not easy for me to say\n"
    .string "this, but…\p"
    .string "Is there some reason why your\n"
    .string "POKéMON would hate you so much?$"

\.Euh, c'est dur à\n
dire\.\pn
Y'a une raison pour\n
que ton PKM te haïsse?

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“The lovely and sweet\n"
    .string "CLEFAIRY”$"

“La jolie et douce\n
MELOFEE”