PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

[player] a joué à la NES.\pn
\.OK!\n
C'est l'heure!

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice\.\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

C'est une affiche\.\pn
Si tu es perdu, demande AIDE!\n
Appuie sur L ou R!