@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "It's crammed full of POKéMON\n"
	.string "books.$"

Plein de livres PKM\n
.

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "A TOWN MAP.$"

UNE CARTE.

Text_PokeMartShelf::
	.string "Wow!\n"
	.string "Tons of POKéMON stuff!$"

Wa!\n
Plein de trucs PKM!

Text_DishesPlatesNeatlyLinedUp::
	.string "Dishes and plates are neatly\n"
	.string "lined up.$"

Assiettes et plats bien\n
rangés.

Text_Kitchen::
	.string "It smells delicious!\n"
	.string "Somebody's been cooking here.$"

Ca sent bon!\n
Qqun a cuisiné ici.

Text_Dresser::
	.string "It's a nicely made dresser.\n"
	.string "It will hold a lot of stuff.$"

C'est une belle commode.\n
On peut y mettre bcp.

Text_Snacks::
	.string "There's a pile of snacks here.$"

Il y a des snacks ici.

Text_PokemartSign::
	.string "All your item needs fulfilled!\n"
	.string "POKéMON MART$"

Tous vos besoins en objets!\n
SUPER PKM

Text_PokecenterSign::
	.string "Heal Your POKéMON!\n"
	.string "POKéMON CENTER$"

Soignez vos PKM!\n
CENTRE PKM

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "The ultimate goal of TRAINERS!\n"
	.string "POKéMON LEAGUE HQ$"

PLAT. INDIGO\pn
Le but ultime DRESSEURS!\n
QG LIGUE PKM

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "The highest POKéMON authority!\n"
	.string "POKéMON LEAGUE HQ$"

PLAT. INDIGO\pn
La plus haute autorité PKM!\n
QG LIGUE PKM

Text_Food::
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"

Ca doit être plein de bonnes\n
choses à manger.

Text_Blueprints::
	.string "It's a blueprint of some sort.\n"
	.string "It's filled with diagrams and text.$"

C'est une sorte de plan.\n
Plein de diagrammes et texte.

Text_Painting::
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"

C'est une belle image d'un PKM.\n
Il a l'air de se sentir bien.

Text_PowerPlantMachine::
	.string "What could this machine be?\n"
	.string "Better not mess around with it!$"

Qu'est-ce que c'est?\n
Mieux vaut pas y toucher!

Text_Telephone::
	.string "It's a telephone.\n"
	.string "Better not use it.$"

Un téléphone.\n
Ne pas l'utiliser.

Text_Computer::
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"

Mots compliqués et\n
chiffres sans sens\.

Text_AdvertisingPoster::
	.string "It's an advertising poster about\n"
	.string "all kinds of products.$"

C'est une affiche de pub pour\n
plein de produits.

Text_TastyFood::
	.string "Oh, that smells tasty!\n"
	.string "It might get the stomach growling!$"

Oh, ça sent bon!\n
Ca donne faim!

Text_TrashBin::
	.string "Inside this…\n"
	.string "……\p"
	.string "There's nothing here!$"

Dedans\. \n
\.\pn
Il n'y a rien!

Text_Cup::
	.string "It's a cup with a POKéMON mark\n"
	.string "on it.$"

Une tasse avec un logo PKM\n
.

Text_PolishedWindow::
	.string "The window is very well polished.$"

La fenêtre est bien polie.

Text_BeautifulSkyWindow::
	.string "Outside the window…\p"
	.string "The sky looks fantastically\n"
	.string "beautiful.$"

Dehors\. \pn
Le ciel est si beau\n
.

Text_BlinkingLights::
	.string "Lights in different colors are\n"
	.string "flashing on and off.$"

Des lumières de couleurs\n
clignotent.

Text_NeatlyLinedUpTools::
	.string "All sorts of tools are lined up\n"
	.string "neatly.$"

Plein d'outils bien\n
rangés.

Text_ImpressiveMachine::
	.string "It's a machine of some sort.\n"
	.string "It sure is impressive.$"

C'est une machine.\n
Impressionnante.

Text_VideoGame::
	.string "It's the latest video game!\n"
	.string "It sure looks fun!$"

Le dernier jeu vidéo!\n
Ca a l'air cool!

Text_Burglary::
	.string "There are obvious signs of burglary\n"
	.string "here…$"

Signes évidents de vol\n
ici\.

Text_PlayerFacingTVScreen::
	.string "There's a POKéMON on TV!\n"
	.string "It looks like it's having fun.$"

Il y a un PKM à la TV!\n
Il a l'air de s'amuser.