gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

Les divers boutons sont expliqués dans\n
l'ordre d'importance.

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

Déplace le personnage.\n
Sert aussi à choisir des\n
options.

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

Sert à valider, examiner\n
parler, et lire le texte.

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

Sert à sortir, annuler choix,\n
et annuler mode.

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

Appuyez pour ouvrir MENU\n
.

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

Sert à bouger et utiliser\n
un objet enreg.

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

Si vous avez besoin d'aide\n
en jeu, ou pour avancer,\n
Appuyez sur L ou R.

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

Et dis-moi. Es-tu un garçon?\n
Ou une fille?

gPikachuIntro_Text_Page1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

Dans le monde où tu vas\n
entrer, tu vivras une grande\n
aventure en héros.\n
\n
Parle aux gens et examine\n
partout: villes, routes,\n
grottes. Cherche des infos\n
partout.

gPikachuIntro_Text_Page2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
.string "Be brave and keep pushing on.$"

Aide les gens, et de nouveaux\n
chemins s'ouvriront, en\n
résolvant des mystères.\n
\n
Parfois, tu seras défié par\n
d'autres ou des créatures.\n
Sois brave et persévère.

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

Pendant ton aventure, on\n
espère que tu vas rencontrer\n
plein de gens et grandir.\n
C'est notre but principal.\n
\n
Appuie sur A, et\n
que ça commence!

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hello, there!\n"
    .string "Glad to meet you!\p"
    .string "Welcome to the world of POKéMON!\p"
    .string "My name is OAK.\p"
    .string "People affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

Bonjour!\n
Ravi de te voir!\pn
Bienvenue dans le monde POKéMON!\pn
Je suis CHEN.\pn
Les gens m'appellent\n
le PROF POKéMON.\pn

gOakSpeech_Text_ThisWorld::
    .string "This world\.$"

Ce monde\.

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

\.est peuplé de\n
créatures: POKéMON.\pn

gOakSpeech_Text_IStudyPokemon::
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I study POKéMON as a profession.\p$"

Certains en font des animaux\n
d'autres les font combattre.\pn
Moi\.\pn
J'étudie les POKéMON.\pn

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

Mais d'abord, parle-moi un peu\n
de toi.\pn

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

Commençons par ton nom.\n
C'est quoi?\pn

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

Ok\.\n
Donc, tu es [player].

gOakSpeech_Text_WhatWasHisName::
    .string "This is my grandson.\p"
    .string "He's been your rival since you both\n"
    .string "were babies.\p"
    .string "…Erm, what was his name now?$"

Mon petit-fils.\pn
C'est ton rival depuis\n
l'enfance.\pn
…Euh, c'est quoi son nom?

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Your rival's name, what was it now?$"

Le nom de ton rival, c'est quoi?

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

…[rival], c'est ça?

gOakSpeech_Text_RememberRivalsName::
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

C'est vrai! J'm'en souviens!\n
Son nom est [rival]!\pn

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Your very own POKéMON legend is\n"
    .string "about to unfold!\p"
    .string "A world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"

[player]\pn
Ta propre légende POKéMON\n
va commencer!\pn
Un monde de rêves, d'aventures\n
POKéMON t'attend! C'est parti!