Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKé DUDE: The speedier of the\n"
	.string "battlers gets to attack first.$"

M. POKé: Le plus rapide\n
frappe en premier.

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "It looks like my RATTATA was\n"
	.string "faster than the PIDGEY.$"

Mon RATTATA était plus\n
rapide que ROUCOOL.

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "The battlers take turns attacking\n"
	.string "and reducing each other's HP.$"

Les rivaux attaquent tour à\n
tour et baissent leurs PV.

Pokedude_Text_MyRattataWonGetsEXP::
	.string "My RATTATA reduced the foe's HP\n"
	.string "to zero, so it wins!\p"
	.string "The POKéMON that took part in the\n"
	.string "battle get EXP. Points.\p"
	.string "When a POKéMON collects enough\n"
	.string "EXP. Points, it levels up.\p"
	.string "Leveling up makes your POKéMON\n"
	.string "stronger than before.$"

Mon RATTATA a mis K.O. l'ennemi\n
donc il gagne!\pn
Le PKM qui a combattu\n
gagne des Points EXP.\pn
Si un PKM gagne assez\n
d'EXP., il monte niveau.\pn
Monter de niv. rend ton PKM\n
plus fort qu'avant.

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKé DUDE: Uh-oh…\n"
	.string "My RATTATA has been poisoned…\p"
	.string "If a POKéMON is poisoned, it loses\n"
	.string "HP steadily.$"

M. POKé: Oh-oh\. \n
Mon RATTATA est empoisonné\. \pn
Si un PKM est empoisonné, il\n
perd des PV.

Pokedude_Text_HealStatusRightAway::
	.string "If a POKéMON develops a status\n"
	.string "problem, heal it right away.$"

Si un PKM a un problème\n
de statut, soigne-le.

Pokedude_Text_UsingItemTakesTurn::
	.string "Using an item on a POKéMON uses\n"
	.string "up one turn, though.\p"
	.string "Now, it's the opponent's turn!$"

Utiliser un objet sur un PKM\n
prend un tour.\pn
C'est au tour de l'ennemi!

Pokedude_Text_YayWeManagedToWin::
	.string "Yay!\n"
	.string "We managed to win!$"

OK!\n
On a pu gagner!

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKé DUDE: The move BUBBLE is\n"
	.string "a WATER-type attack.\p"
	.string "The targeted ODDISH is a\n"
	.string "GRASS/POISON-type POKéMON.\p"
	.string "The WATER-type attack is absorbed\n"
	.string "by the GRASS-type POKéMON…\p"
	.string "As a result, the move becomes not\n"
	.string "very effective, and inflicts only\l"
	.string "half the usual damage.$"

M. POKé: L'att. ECUME est\n
une attaque EAU.\pn
Le MYSTHERBE ciblé est\n
un PKM PLANTE/POISON.\pn
L'attaque EAU est absorbée\n
par le PKM PLANTE\. \pn
Du coup, l'att. n'est pas\n
très efficace, et fait 1/2\l
dégâts normaux.

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Uh-oh, this is not good!\p"
	.string "The ABSORB attack you just saw\n"
	.string "is a GRASS-type move.\p"
	.string "POLIWAG is a WATER-type POKéMON.\p"
	.string "So, ABSORB becomes super\n"
	.string "effective, doubling the damage.$"

Oh-oh, c'est pas bon!\pn
L'att. VOL-VIE que tu as vue\n
est un move PLANTE.\pn
PTITARD est un PKM EAU.\pn
Donc, VOL-VIE est super\n
efficace, doublant les dégâts.

Pokedude_Text_LetsTryShiftingMons::
	.string "It's not going to be easy to win\n"
	.string "with this matchup…\p"
	.string "Let's try shifting POKéMON!$"

Ce ne sera pas facile de\n
gagner\. \pn
Essayons de changer de PKM!

Pokedude_Text_ShiftingUsesTurn::
	.string "Shifting POKéMON in and out uses\n"
	.string "up one turn.\p"
	.string "Now, it's the opponent's turn.$"

Changer de PKM utilise\n
un tour.\pn
C'est au tour de l'ennemi.

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "BUTTERFREE is a BUG/FLYING-type\n"
	.string "POKéMON.\p"
	.string "Against this POKéMON, a GRASS-\n"
	.string "type attack…\p"
	.string "…inflicts only half the usual\n"
	.string "damage on a BUG-type POKéMON…\p"
	.string "…And, it also causes only half the\n"
	.string "damage on a FLYING-type POKéMON.\p"
	.string "Therefore, BUTTERFREE, being a\n"
	.string "BUG/FLYING POKéMON, only takes\l"
	.string "one quarter of the usual damage.$"

PAPILUSION est type INSEC/VOL\n
PKM.\pn
Contre ce PKM, att. PLANTE\n
-\pn
\.fait 1/2 dégâts\n
sur un PKM INSECTE\. \pn
\.Et, cause aussi 1/2\n
dégâts sur un PKM VOL.\pn
Donc, PAPILUSION, est\n
PKM INSEC/VOL, prend 1/4\l
des dégâts normaux.

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "ODDISH is a GRASS/POISON-type\n"
	.string "POKéMON.\p"
	.string "A FLYING- or PSYCHIC-type attack\n"
	.string "is super effective against it.\p"
	.string "One of those types of attacks will\n"
	.string "inflict double the usual damage.\p"
	.string "Okay, here we go!$"

MYSTHERBE est PLANTE/POISON\n
PKM.\pn
Une att. VOL ou PSY\n
est super efficace.\pn
Un de ces types d'attaques\n
fera le double de dégâts.\pn
OK, on y va!

Pokedude_Text_YeahWeWon::
	.string "Yeah!\n"
	.string "We won!$"

Oui!\n
Gagné!

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKé DUDE: When you're trying to\n"
	.string "catch a POKéMON, don't throw any\l"
	.string "POKé BALLS right away.\p"
	.string "First, you need to weaken it by\n"
	.string "reducing its HP.$"

M. POKé: Si tu tentes\n
d'attraper un PKM, ne lance\l
pas de BALL direct.\pn
D'abord, affaiblis-le en\n
baissant ses PV.

Pokedude_Text_BestIfTargetStatused::
	.string "Okay, that should be good enough.\p"
	.string "But, if it's possible, it would be\n"
	.string "best if the target has a status\l"
	.string "problem.\p"
	.string "For instance, it would be easier\n"
	.string "to catch if it were asleep or\l"
	.string "paralyzed.$"

OK, ça devrait suffire.\pn
Mais, si c'est possible, il\n
vaut mieux qu'il ait un\l
statut.\pn
Exemple, ce serait +facile\n
de l'avoir endormi ou\l
paralysé.

Pokedude_Text_CantDoubleUpOnStatus::
	.string "This will make the POKéMON a lot\n"
	.string "easier to catch!\p"
	.string "Oh, yes. If you paralyze a\n"
	.string "POKéMON, you can't make it fall\l"
	.string "asleep on top of paralysis.\p"
	.string "In other words, you can't double\n"
	.string "up status problems, okay?$"

Ca rendra le PKM bien\n
plus simple!\pn
Ah. Si tu paralyses\n
un PKM, tu ne peux pas\l
l'endormir en plus.\pn
En gros, tu ne peux pas cumuler\n
les statuts, OK?

Pokedude_Text_LetMeThrowBall::
	.string "Okay!\n"
	.string "Let me throw my POKé BALL!$"

OK!\n
Je lance ma POKé BALL!

Pokedude_Text_PickBestKindOfBall::
	.string "Before you throw a POKé BALL,\n"
	.string "consider the condition and the\l"
	.string "type of POKéMON, and pick the kind\l"
	.string "of BALL that would work best.$"

Avant de lancer une BALL,\n
vois l'état et le\l
type du PKM, et choisis\l
la BALL la mieux.