PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: What, it's only {PLAYER}?\n"
    .string "Gramps isn't around.$"

[rival]: Quoi, c'est [player]?\n
Papy n'est pas là.

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Gramps!\n"
    .string "I'm fed up with waiting!$"

[rival]: Papy!\n
J'en ai marre d'attendre!

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Hey! Gramps! No fair!\n"
    .string "What about me?$"

[rival]: Hé! Papy! Pas juste!\n
Et moi alors?

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Heh, I don't need to be\n"
    .string "greedy like you. I'm mature!\p"
    .string "Go ahead and choose, {PLAYER}!$"

[rival]: J'ai pas besoin\n
d'être avide. Je suis mûr!\pn
Vas-y, choisis, [player]!

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: I'll take this one, then!$"

[rival]: Je prends celui-là!

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} received the {STR_VAR_1}\n"
    .string "from PROF. OAK!$"

[rival] reçoit [STR_VAR_1]\n
du PR. CHEN!

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: My POKéMON looks a lot\n"
    .string "tougher than yours.$"

[rival]: Mon PKM a l'air\n
plus fort que toi.

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Wait, {PLAYER}!\n"
    .string "Let's check out our POKéMON!\p"
    .string "Come on, I'll take you on!$"

[rival]: Stop, [player]!\n
Vérifions nos PKM!\pn
Viens, je te défie!

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "WHAT?\n"
    .string "Unbelievable!\l"
    .string "I picked the wrong POKéMON!$"

Non!\n
Pas possible!\l
Je me suis trompé de PKM!

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Yeah!\n"
    .string "Am I great or what?$"

[rival]: YES!\n
Je suis fort, non?

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Okay! I'll make my\n"
    .string "POKéMON battle to toughen it up!\p"
    .string "{PLAYER}! Gramps!\n"
    .string "Smell you later!$"

[rival]: OK! Je vais\n
faire combattre mon PKM!\pn
[player]! Papy!\n
A plus tard!

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Gramps!$"

[rival]: Papy!

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: I almost forgot!\n"
    .string "What did you call me for?$"

[rival]: J'allais oublier!\n
Tu m'appelais pourquoi?

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: All right, Gramps!\n"
    .string "Leave it all to me!$"

[rival]: Très bien, Papy!\n
Laisse-moi faire!

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, I hate to say it, but you\n"
    .string "won't be necessary for this.\p"
    .string "I know! I'll borrow a TOWN MAP\n"
    .string "from my sis!\p"
    .string "I'll tell her not to lend you one,\n"
    .string "{PLAYER}! Hahaha!\p"
    .string "Don't bother coming around to\n"
    .string "my place after this!$"

[player], désolé, mais tu\n
n'es pas utile ici.\pn
Je sais! Je prends la CARTE\n
à ma soeur!\pn
Je lui dirai de pas t'en prêter,\n
[player]! Ha!Ha!\pn
Pas la peine de venir\n
chez moi après ça!

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: {RIVAL}?\n"
    .string "Let me think…\p"
    .string "Oh, that's right, I told you to\n"
    .string "come! Just wait!\p"
    .string "Here, {PLAYER}.\p"
    .string "There are three POKéMON here.\p"
    .string "Haha!\p"
    .string "The POKéMON are held inside\n"
    .string "these POKé BALLS.\p"
    .string "When I was young, I was a serious\n"
    .string "POKéMON TRAINER.\p"
    .string "But now, in my old age, I have\n"
    .string "only these three left.\p"
    .string "You can have one.\n"
    .string "Go on, choose!$"

C.: [rival]?\n
Attends\.\pn
Ah, oui, je t'avais dit\n
de venir! Stop!\pn
Ici, [player].\pn
Il y a 3 PKM ici.\pn
Ha!\pn
Les PKM sont dans\n
ces POKé BALLS.\pn
Jeune, j'étais un DRESSEUR\n
PKM sérieux.\pn
Mais vieux, il me reste\n
que ces 3 là.\pn
Prends-en un.\n
Vas-y, choisis!

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: Be patient, {RIVAL}.\n"
    .string "You can have one, too!$"

C.: Patiente, [rival].\n
Tu en auras un aussi!

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: Now, {PLAYER}.\p"
    .string "Inside those three POKé BALLS are\n"
    .string "POKéMON.\p"
    .string "Which one will you choose for\n"
    .string "yourself?$"

C.: Bon, [player].\pn
Dans ces 3 POKé BALLS se\n
trouvent\pn
Lequel vas-tu choisir\n
pour toi?

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: Hey!\n"
    .string "Don't go away yet!$"

C.: Hé!\n
Ne pars pas!

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! CHARMANDER is your choice.\n"
    .string "You should raise it patiently.\p"
    .string "So, {PLAYER}, you're claiming the\n"
    .string "FIRE POKéMON CHARMANDER?$"

Ah! Tu choisis SALAMECHE.\n
Tu devrais l'élever sagement.\pn
Donc, [player], tu prends\n
le PKM FEU SALAMECHE?

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! SQUIRTLE is your choice.\n"
    .string "It's one worth raising.\p"
    .string "So, {PLAYER}, you've decided on the\n"
    .string "WATER POKéMON SQUIRTLE?$"

Hm! Tu choisis CARAPUCE.\n
Il vaut le coup.\pn
Donc, [player], tu choisis\n
le PKM EAU CARAPUCE?

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "I see! BULBASAUR is your choice.\n"
    .string "It's very easy to raise.\p"
    .string "So, {PLAYER}, you want to go with\n"
    .string "the GRASS POKéMON BULBASAUR?$"

Je vois! Tu choisis BULBIZARRE.\n
Très facile à élever.\pn
Donc, [player], tu veux\n
le PKM PLANTE BULBIZARRE?

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "This POKéMON is really quite\n"
    .string "energetic!$"

Ce PKM est vraiment\n
énergique!

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from PROF. OAK!$"

[player] reçoit [STR_VAR_1]\n
du PR. CHEN!

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: If a wild POKéMON appears,\n"
    .string "your POKéMON can battle it.\p"
    .string "With it at your side, you should be\n"
    .string "able to reach the next town.$"

C.: Si un PKM sauvage\n
ton PKM peut le battre.\pn
Avec lui, tu devrais\n
atteindre la ville proche.

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: {PLAYER}, raise your young\n"
    .string "POKéMON by making it battle.\p"
    .string "It has to battle for it to grow.$"

C.: [player], élève ton\n
PKM par le combat.\pn
Il doit combattre pour grandir.

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Oh, {PLAYER}!\n"
    .string "How is my old POKéMON?\p"
    .string "Well, it seems to be growing more\n"
    .string "attached to you.\p"
    .string "You must be talented as a POKéMON\n"
    .string "TRAINER.\p"
    .string "What's that?\n"
    .string "You have something for me?$"

C.: Oh, [player]!\n
Va bien, mon PKM?\pn
On dirait qu'il s'attache\n
à toi.\pn
Tu dois être un DRESSEUR\n
doué.\pn
Qu'est-ce?\n
Tu as un truc pour moi?

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} delivered OAK'S PARCEL.$"

[player] a livré COLIS PR CHEN.

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah! \n"
    .string "It's the custom POKé BALL!\p"
    .string "I had it on order.\n"
    .string "Thank you!$"

Ah!\n
C'est la POKé BALL!\pn
Je l'ai commandée.\n
Merci!

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Oh, right!\n"
    .string "I have a request for you two.$"

C.: Ah, oui!\n
J'ai un service à vous 2.

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "On the desk there is my invention,\n"
    .string "the POKéDEX!\p"
    .string "It automatically records data on\n"
    .string "POKéMON you've seen or caught.\p"
    .string "It's a high-tech encyclopedia!$"

Sur le bureau, mon invention,\n
le POKéDEX!\pn
Il enregistre auto. les données\n
PKM vus ou attrapés.\pn
Une encyclo. high-tech!

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} and {RIVAL}.\n"
    .string "Take these with you.$"

C.: [player] et [rival].\n
Prenez ceci.

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} received the POKéDEX\n"
    .string "from PROF. OAK.$"

[player] a reçu le POKéDEX\n
du PR. CHEN.

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: You can't get detailed data\n"
    .string "on POKéMON by just seeing them.\p"
    .string "You must catch them to obtain\n"
    .string "complete data.\p"
    .string "So, here are some tools for\n"
    .string "catching wild POKéMON.$"

C.: Tu n'as pas de données\n
PKM en les voyant.\pn
Tu dois les attraper pour\n
tout savoir.\pn
Donc, voici des outils pour\n
capturer PKM.

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} received five POKé BALLS.$"

[player] reçoit 5 POKé BALLS.

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "When a wild POKéMON appears,\n"
    .string "it's fair game.\p"
    .string "Just throw a POKé BALL at it and\n"
    .string "try to catch it!\p"
    .string "This won't always work, however.\p"
    .string "A healthy POKéMON can escape.\n"
    .string "You have to be lucky!$"

Si un PKM sauvage surgit,\n
c'est le jeu.\pn
Lance une POKé BALL dessus et\n
tente le coup!\pn
Ca ne marche pas toujours.\pn
Un PKM sain peut fuir.\n
Tu dois avoir du bol!

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "To make a complete guide on all\n"
    .string "the POKéMON in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old.\n"
    .string "I can't get the job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "POKéMON history!$"

Faire un guide complet sur\n
tous les PKM du monde\.\pn
C'était mon rêve!\pn
Suis trop vieux.\n
Je ne peux plus le faire.\pn
Donc, je veux que vous 2\n
le fassiez.\pn
En route, vous deux.\pn
C'est une grande mission de\n
l'hist. PKM!

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON around the world wait for\n"
    .string "you, {PLAYER}!$"

Les PKM du monde attendent\n
[player]!

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

Ah, [player]!\n
Où en est ton POKéDEX?\pn
[rival] a déjà attrapé des\n
PKM et mis à jour.\pn
Donc, [player], voyons\n
ton POKéDEX.\pn
\.Quoi?\n
Tu n'as rien ajouté.\pn
Je te donne ça, essaie\n
un peu plus.

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"

C.: Viens me voir.\pn
Je veux savoir où en est\n
ton POKéDEX.

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

C'est une encyclo, mais\n
blanche.

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Those are POKé BALLS.\n"
    .string "They contain POKéMON!$"

Des POKé BALLS.\n
Avec des PKM!

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "That's PROF. OAK's last POKéMON.$"

C'est le PKM du PR. CHEN.

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Press START to open the MENU!$"

Appuie START pour le MENU!

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "The SAVE option is on the MENU.\n"
    .string "Use it regularly.$"

SAUVEG. est sur le MENU.\n
Fais-le souvent.

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "All POKéMON types have strong and\n"
    .string "weak points against others.$"

Chaque type PKM a forces\n
et faiblesses.

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "Finally!\n"
    .string "The ultimate TRAINERS of the\l"
    .string "POKéMON LEAGUE are ready to\l"
    .string "take on all comers!\p"
    .string "Bring your best POKéMON and see\n"
    .string "how you rate as a TRAINER!\p"
    .string "POKéMON LEAGUE HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, please visit us!\n"
    .string "…$"

Il y a un e-mail ici.\pn
\.\pn
Enfin!\n
Les DRESSEURS ultimes de\l
la LIGUE PKM sont\l
prêts!\pn
Amène tes PKM et vois\n
ton niveau DRESSEUR!\pn
QG LIGUE POKéMON\n
PLAT. INDIGO\pn
PR. CHEN, venez nous voir!\n
\.

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "I study POKéMON as PROF. OAK's\n"
    .string "AIDE.$"

J'étudie PKM pour PR. CHEN\n
AIDE.

PalletTown_ProfessorOFaksLab_Text_DaisyWillGroomMons::
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

Salut [player]. Je parie que\n
tu es ami avec tes PKM.\pn
Au fait, tu connais\n
NINA?\pn
Si tu montres à NINA tes PKM,\n
elle voit s'ils t'aiment.\pn
Parfois, elle va même\n
toilett. un PKM.\pn
C'est un secret, donc ne\n
le dis pas.

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called PROF.\n"
    .string "OAK's POKéMON SEMINAR.$"

PR. CHEN va avoir sa\n
propre radio.\pn
L'émission sera PR.\n
SEMINAIRE PKM CHEN.

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PROF. OAK may not look like much,\n"
    .string "but he's the authority on POKéMON.\p"
    .string "Many POKéMON TRAINERS hold him in\n"
    .string "high regard.$"

PR. CHEN ne paie pas de mine,\n
mais c'est l'expert PKM.\pn
Plein de DRESSEURS PKM\n
le respecte.

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

Ah, c'est excellent!\pn
[player], j'ai un autre\n
service à te dder.\pn
Tu dois bien écouter.

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

Récemment, on a vu\n
des PKM rares.\pn
Je parle de PKM\n
jamais vus à KANTO.\pn
J'aimerais aller voir\n
moi-même, mais trop vieux.\pn
Comme je peux pas, [player],\n
j'aimerais que tu y ailles.

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more POKéMON,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

[rival]: Hé, j'ai entendu!\pn
Papy, pourquoi tu préfères\n
[player] à moi?\pn
J'ai attrapé plus de PKM,\n
et plus vite.\pn
Tu devrais me laisser tout\n
gérer.

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"

C.: Je sais, je sais.\n
J'ai aussi besoin de toi.\pn
Je dois voir vos deux\n
POKéDEX.

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK took both POKéDEX\n"
    .string "units.$"

PR. CHEN prend les POKéDEX\n
.

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"

\. \. \. \. \. \.\pn
\. \. \. \. \. \.\pn
\.Et voilà!\pn
Ils peuvent enreg. données\n
de plus de PKM.

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'s POKéDEX was upgraded!$"

POKéDEX de [player] amélioré!

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"

Bon, [player] et [rival]!\pn
Cette fois, vous devez\n
remplir vos POKéDEX.\pn
Je veux les meilleurs\n
et les plus complets!\pn
C'est une tâche monumentale\n
de l'histoire PKM!

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"

[rival]: Papy, calme-toi.\n
T'excite pas.\pn
Je vais finir le POKéDEX,\n
ne t'en fais pas.\pn
Je vais aller voir sur\n
l'ILE UNE\.\pn
Bref, j'y vais!