Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Salut!\n
Je bosse à la BOUT. PKM.\pn
C'est une chaîne pratique\n
vendant plein d'objets.\pn
Viens nous voir à JADIELLE.\pn
Je sais, je te donne un échant.\n
Et voilà!

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Viens nous voir si tu as besoin\n
de POKé BALLS pour PKM.

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

[player] range la POTION\n
dans son SAC.

Route1_Text_CanJumpFromLedges::
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to PALLET TOWN\n"
    .string "quicker that way.$"

Tu vois ces rebords sur la route?\pn
Ca fait peur, mais tu peux sauter\n
d'ici.\pn
Tu peux rentrer à BOURG PALETTE\n
plus vite ainsi.

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"

ROUTE 1\n
BOURG PALETTE - JADIELLE