PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

MAMAN: \.Ok.\n
Un garçon part un jour.\l
Vu à la TV.\pn
Oh, oui. Le PR. CHEN, ton voisin,\n
te cherchait.

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

MAMAN: \.Ok.\n
Toute fille rêve de voyage.\l
Vu à la TV.\pn
Oh, oui. Le PR. CHEN, ton voisin,\n
te cherchait.

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

[player]!\n
Tu devrais te reposer.

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

MAMAN: Oh! Toi et tes\n
POKéMON semblez super.\l
Fais attention.

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

Il y a un film à la TV.\n
Quatre garçons marchent sur\l
la voie.\pn
\.J'y vais aussi.

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

Il y a un film à la TV.\n
Une fille avec des couettes\l
marche sur un chemin.\pn
\.J'y vais aussi.

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

Oups, de l'autre.