PalletTown_Text_OakDontGoOut::
    .string "OAK: Hey! Wait!\n"
    .string "Don't go out!$"

CHEN: Hé! Attends!\n
Ne sors pas!

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: It's unsafe!\n"
    .string "Wild POKéMON live in tall grass!\p"
    .string "You need your own POKéMON for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

CHEN: C'est risqué!\n
POKéMON sauvages vivent là!\pn
Tu as besoin d'un POKéMON\n
pour te protéger.\pn
Je sais!\n
Viens avec moi!

PalletTown_Text_RaisingMonsToo::
    .string "I'm raising POKéMON, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

J'élève des POKéMON.\pn
Quand ils sont forts, ils\n
me protègent.

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"

La science est super!\pn
Tu peux stocker objets\n
et POKéMON sur PC.

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON RESEARCH LAB$"

LABO RECHERCHE PKM CHEN

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

Maison de [player]

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

Maison de [rival]

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"

BOURG PALETTE\n
L'aventure t'attend!

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

CHEN: Ah, [player]!\n
Te voilà de retour?\pn
Où en est ton\n
POKéDEX?\pn
Puis-je voir?\pn
Voyons\.

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

Tu as [STR_VAR_2]\.\pn
Hm, tu sembles faire\n
un effort honnête.\pn
Quand tu l'auras un peu\n
plus rempli, reviens.

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

Tu as\. [STR_VAR_2]!?\n
Ca, c'est super!\pn
J'ai une chose pour\n
toi, [player].\pn
Ici.\n
Suis-moi.

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

CHEN: Ah, [player]!\n
Tu aimes voyager.\pn
Te connaissant, [player],\n
je t'imagine voir plus\l
de lieux.\pn
Tant mieux, tant mieux.\n
Hohoho.